### ISSUE TITLE
Morning Session Suggestions

### ISSUE THREAD

**Issue by topeogunleye** [topeogunleye/conference-page#5]
Morning Session Suggestions

**Comment by vic778** [comment]
hey @topeogunleye 
-  your code is perfectly represented. you have respected all the recommendations for writing professional code but
-  I advise you to review the logo in the mobile version. it turns out that it confuses the navbar that's why it is not too advisable to use it in the mobile version.  I advise you to review the logo in the mobile version. it turns out that it confuses the navbar that's why it is not too advisable to use it in the mobile version.
 Happy coding bro

**Comment by edwardoluyara** [comment]
@topeogunleye 
All recommendations passed, clean code, nice layout "Great Job man!"

**Comment by topeogunleye** [comment]
Hey @vic778 and @oluyaratosin123 , thank you for taking the time to check out my project. 🙏🏻
I'll definitely consider your feedback.
